### ISSUE TITLE
Error regarding package 'genefilter'

### ISSUE THREAD

**Issue by dkioroglou** [andreasmock/MetaboDiff#2]
Hello and thank you for creating this package.
I have the following question:
I have used the function "diff_test" on a dataset and I got the following error:

```
Error in loadNamespace(name) : there is no package called ‘genefilter’
```

I have used this function before on a different dataset and it worked just fine.
Do you have any idea why I get suddenly this error?

Thank you in advance.

**Comment by ManjotVirdee** [comment]
Hello,

I have also had problems running the `diff_test()`function. My error is:
> unable to find an inherited method for function ‘rowttests’

This a function native to `genefilter` and my solution is to load `genefilter` before running `diff_test()` through `> library(genefilter)`. I am not sure if this will solve your problem though, but give it a try and let me know. 

Best,
M. Virdee

**Comment by andreasmock** [comment]
Hi everyone,

I have added the `genefilter` package to the NAMESPACE. This should fix the problem you encountered. 

Best regards,
Andreas
